#!/bin/bash
# =============================================================================
# 04-s3-cloudfront.sh — Create S3 bucket + CloudFront CDN for static assets
# Run from your LOCAL machine (needs AWS CLI configured with ap-south-1)
# =============================================================================
set -euo pipefail

BUCKET_NAME="apkaai-assets"
REGION="ap-south-1"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

echo "=============================================="
echo "  ApkaAI — S3 + CloudFront Setup"
echo "  Bucket : $BUCKET_NAME"
echo "  Region : $REGION"
echo "  Account: $ACCOUNT_ID"
echo "=============================================="

# ── 1. Create S3 bucket ────────────────────────────────────────────────────────
echo "[1/6] Creating S3 bucket: $BUCKET_NAME..."

aws s3api create-bucket \
  --bucket "$BUCKET_NAME" \
  --region "$REGION" \
  --create-bucket-configuration LocationConstraint="$REGION"

# Block all public access (CloudFront will serve via OAC)
aws s3api put-public-access-block \
  --bucket "$BUCKET_NAME" \
  --public-access-block-configuration \
    "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

echo "  ✅ Bucket created: s3://$BUCKET_NAME"

# ── 2. Enable versioning ───────────────────────────────────────────────────────
echo "[2/6] Enabling versioning..."
aws s3api put-bucket-versioning \
  --bucket "$BUCKET_NAME" \
  --versioning-configuration Status=Enabled

# ── 3. Create CloudFront Origin Access Control ─────────────────────────────────
echo "[3/6] Creating CloudFront Origin Access Control (OAC)..."
OAC_ID=$(aws cloudfront create-origin-access-control \
  --origin-access-control-config \
    "Name=apkaai-oac,Description=ApkaAI S3 OAC,OriginAccessControlOriginType=s3,SigningBehavior=always,SigningProtocol=sigv4" \
  --query 'OriginAccessControl.Id' \
  --output text)
echo "  OAC ID: $OAC_ID"

# ── 4. Create CloudFront distribution ─────────────────────────────────────────
echo "[4/6] Creating CloudFront distribution..."
DISTRIBUTION_ID=$(aws cloudfront create-distribution \
  --distribution-config "{
    \"CallerReference\": \"apkaai-$(date +%s)\",
    \"Comment\": \"ApkaAI static assets CDN\",
    \"DefaultCacheBehavior\": {
      \"TargetOriginId\": \"S3-$BUCKET_NAME\",
      \"ViewerProtocolPolicy\": \"redirect-to-https\",
      \"CachePolicyId\": \"658327ea-f89d-4fab-a63d-7e88639e58f6\",
      \"Compress\": true,
      \"AllowedMethods\": {
        \"Quantity\": 2,
        \"Items\": [\"HEAD\", \"GET\"],
        \"CachedMethods\": { \"Quantity\": 2, \"Items\": [\"HEAD\", \"GET\"] }
      }
    },
    \"Origins\": {
      \"Quantity\": 1,
      \"Items\": [{
        \"Id\": \"S3-$BUCKET_NAME\",
        \"DomainName\": \"$BUCKET_NAME.s3.$REGION.amazonaws.com\",
        \"OriginAccessControlId\": \"$OAC_ID\",
        \"S3OriginConfig\": { \"OriginAccessIdentity\": \"\" }
      }]
    },
    \"Enabled\": true,
    \"HttpVersion\": \"http2\",
    \"PriceClass\": \"PriceClass_200\"
  }" \
  --query 'Distribution.Id' \
  --output text)

CLOUDFRONT_DOMAIN=$(aws cloudfront get-distribution \
  --id "$DISTRIBUTION_ID" \
  --query 'Distribution.DomainName' \
  --output text)

echo "  Distribution ID: $DISTRIBUTION_ID"
echo "  CloudFront URL : https://$CLOUDFRONT_DOMAIN"

# ── 5. Attach bucket policy to allow CloudFront OAC ──────────────────────────
echo "[5/6] Attaching S3 bucket policy for CloudFront OAC..."
aws s3api put-bucket-policy \
  --bucket "$BUCKET_NAME" \
  --policy "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [{
      \"Sid\": \"AllowCloudFrontOAC\",
      \"Effect\": \"Allow\",
      \"Principal\": { \"Service\": \"cloudfront.amazonaws.com\" },
      \"Action\": \"s3:GetObject\",
      \"Resource\": \"arn:aws:s3:::$BUCKET_NAME/*\",
      \"Condition\": {
        \"StringEquals\": {
          \"AWS:SourceArn\": \"arn:aws:cloudfront::$ACCOUNT_ID:distribution/$DISTRIBUTION_ID\"
        }
      }
    }]
  }"

# ── 6. Upload sample assets ────────────────────────────────────────────────────
echo "[6/6] Creating sample folder structure in S3..."
echo "apkaai.com" | aws s3 cp - "s3://$BUCKET_NAME/placeholder.txt"
aws s3api put-object --bucket "$BUCKET_NAME" --key "images/"     --content-length 0
aws s3api put-object --bucket "$BUCKET_NAME" --key "logos/"      --content-length 0
aws s3api put-object --bucket "$BUCKET_NAME" --key "thumbnails/" --content-length 0

# ── Save config for reference ──────────────────────────────────────────────────
cat > "$(dirname "$0")/s3-cloudfront-config.txt" << EOF
# Generated by 04-s3-cloudfront.sh on $(date)
S3_BUCKET=$BUCKET_NAME
S3_REGION=$REGION
CLOUDFRONT_DISTRIBUTION_ID=$DISTRIBUTION_ID
CLOUDFRONT_DOMAIN=$CLOUDFRONT_DOMAIN
CDN_BASE_URL=https://$CLOUDFRONT_DOMAIN
EOF

echo ""
echo "✅ S3 + CloudFront setup complete!"
echo ""
echo "  S3 Bucket    : s3://$BUCKET_NAME ($REGION)"
echo "  CloudFront   : https://$CLOUDFRONT_DOMAIN"
echo "  Config saved : deploy/s3-cloudfront-config.txt"
echo ""
echo "  Update your Next.js next.config.js with:"
echo "  images.domains: ['$CLOUDFRONT_DOMAIN']"
echo ""
echo "  ⚠️  CloudFront takes ~10-15 minutes to deploy globally."
